# Generated by Django 2.2.7 on 2019-11-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('class_code', models.CharField(editable=False, max_length=6, unique=True)),
            ],
        ),
    ]
