# Generated by Django 2.2.7 on 2019-11-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0002_auto_20191114_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentId',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
