# Generated by Django 2.2.7 on 2019-11-14 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0003_auto_20191114_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric student IDs (consisting of 0-9) are allowed.')]),
        ),
    ]
