# Generated by Django 2.2.7 on 2019-11-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0004_auto_20191114_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(editable=False)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='headcount_db.Classroom')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='headcount_db.Student')),
            ],
        ),
    ]
