# Generated by Django 2.2.7 on 2019-11-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0005_attendancetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
