# Generated by Django 2.2.7 on 2019-11-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0006_classroom_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='date',
        ),
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
