# Generated by Django 2.2.7 on 2019-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0007_auto_20191120_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
