# Generated by Django 2.2.7 on 2019-11-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0008_auto_20191120_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
