# Generated by Django 2.2.7 on 2019-11-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0009_auto_20191120_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(blank=True, default=None, editable=False, max_length=6, unique=True),
        ),
    ]
