# Generated by Django 2.2.7 on 2019-11-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0013_auto_20191120_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(default=None, editable=False, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, to='headcount_db.Student'),
        ),
    ]
