# Generated by Django 2.2.7 on 2019-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='code',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='title',
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(default='000000', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.CharField(default='XXXX', max_length=4),
        ),
        migrations.AddField(
            model_name='classroom',
            name='number',
            field=models.CharField(default='XXXXX', max_length=5),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='professor',
            field=models.CharField(max_length=200),
        ),
    ]
