# Generated by Django 2.2.7 on 2019-11-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headcount_db', '0002_auto_20191113_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='department',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.CharField(default='', max_length=5),
        ),
    ]
